language: c
os: linux
dist: xenial

matrix:
  include:
    # Build and test against the master (stable) and devel branches of Nim
    - env: NIMVERSION=1.4.0
      services:
        mysql
    - env: NIMVERSION=1.2.6
      services:
        mysql
    - env: NIMVERSION=1.0.2
      services:
        mysql

install:
  - curl https://nim-lang.org/download/nim-$NIMVERSION-linux_x64.tar.xz | xzcat | tar -C "$HOME" -xf -
  - export PATH=$HOME/nim-$NIMVERSION/bin:$HOME/.nimble/bin:$PATH
  - echo "export PATH=$PATH" >> ~/.profile

before_script:
  - mysql -h 127.0.0.1 -u root -e "create database if not exists test;"
  - mysql -h 127.0.0.1 -u root -e "create user 'nimtest'@'127.0.0.1' identified WITH mysql_native_password by '123456';"
  - mysql -h 127.0.0.1 -u root -e "grant all on test.* to 'nimtest'@'127.0.0.1';"

script:
  - nimble check
  - nim c -d:test -d:ssl -r asyncmysql.nim
  - nim c -d:test test_sql.nim
  - ./test_sql --no-ssl -D test -h localhost -u nimtest --password 123456
  - nim c -d:ssl -d:test test_sql.nim
  - ./test_sql --no-ssl -D test -h localhost -u nimtest --password 123456
  - ./test_sql --ssl --allow-mitm -D test -h localhost -u nimtest --password 123456
